### ISSUE TITLE
panic: index out of range

### ISSUE THREAD

**Issue by landryzhi** [gojektech/valkyrie#3]
The implements of Error interface will panic when multi-goroutine both Error and Push, because the formattedError defined outside of mutex and formattedError assign through index (index out of range).

I prefer Error inplement like this:

func (m *MultiError) Error() string {
	m.mu.Lock()
	l := len(m.errs)
	m.mu.Unlock()

	if l == 0 {
		return ""
	}

	formattedError := make([]string, l)
	for i:=0; i<l;i++ {
		formattedError[i] = m.errs[i].Error()
	}

	return strings.Join(formattedError, ",")
}

**Comment by rShetty** [comment]
@landryzhi Plz help raise a PR on this. Thanks

**Comment by gwthm-in** [comment]
Closing this issue as it is fixed in commit 8f62c1e

**Comment by gwthm-in** [comment]
@landryzhi can you confirm whether this issue is fixed for you?

**Comment by landryzhi** [comment]
@gowtham-sai i thought this issue is fixed, but the lock scope smaller will be better?

**Comment by gwthm-in** [comment]
@landryzhi do you mean locking and unlocking in inner loop?
